title: LMS Plus / LMS+
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
#include: ['_pages']
page_excerpts: true

collections:
  pages:
    output: true
    permalink: /warehouse/:path/

github:
  is_project_page: false
