title: LMS Plus / LMS+
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
timezone: "Europe/Warsaw"

defaults:
  -
     scope:
       path: "wiki"
       type: "pages"
     values:
       permalink: /:basename

github:
  is_project_page: false
