title: LMS Plus / LMS+
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
# (boolean) Enable/disable wiki page list in sidebar
#show_wiki_pages: true
# (integer) Maximum number of wiki page to shown in sidebar
#show_wiki_pages_limit: 10
# (boolean) Enable/disable blog feature
#blog_feature: false
# (boolean) Enable/disable wiki posts list in sidebar (needs blog_feature enabled)
#show_wiki_posts: false
# (integer) Maximum number of wiki posts to shown in sidebar
#show_wiki_posts_limit: 10
# (boolean) Enable/disable download buttons in sidebar
#show_downloads: true
# (string) Specify branch rendered by gitpages allowing wiki tool buttons to work
#git_branch: "master"
# (string) folder where wiki pages are stored, it's needed for tool buttons
#wiki_folder: "wiki"
# (boolean) if you're using github wiki as submodule then this config
# must be enabled to allow tool buttons to work properly
use_github_wiki: false
timezone: "Europe/Warsaw"

defaults:
  -
     scope:
       path: "wiki"
     values:
       permalink: /:basename
       layout: default

github:
  is_project_page: false
