title: LMS Plus / LMS+
logo: /assets/img/logo.png
theme: jekyll-theme-minimal
include: ['_warehouse']
page_excerpts: true

collections:
  warehouse:
    output: true
    permalink: /:path

github:
  is_project_page: false
